/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author marcelo
 */
public class Login extends javax.swing.JFrame {
    
    int LayoutX, LayoutY;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_bg = new javax.swing.JPanel();
        lbl_bem_vindo = new javax.swing.JLabel();
        lbl_sub = new javax.swing.JLabel();
        pwf_senha = new javax.swing.JPasswordField();
        txf_usuario = new javax.swing.JTextField();
        lbl_esqueci_senha = new javax.swing.JLabel();
        btn_entrar = new javax.swing.JButton();
        lbl_sub1 = new javax.swing.JLabel();
        lbl_esqueci_senha1 = new javax.swing.JLabel();
        pnl_title_bar = new javax.swing.JPanel();
        btn_minimizar = new javax.swing.JButton();
        btn_sair = new javax.swing.JButton();
        lbl_avatar = new javax.swing.JLabel();
        lbl_user_icon = new javax.swing.JLabel();
        lbl_padlock = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projeto Ferias");
        setUndecorated(true);
        setResizable(false);

        pnl_bg.setBackground(new java.awt.Color(0, 2, 50));

        lbl_bem_vindo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lbl_bem_vindo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_bem_vindo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_bem_vindo.setText("Bem Vindo");
        lbl_bem_vindo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbl_sub.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl_sub.setForeground(new java.awt.Color(94, 100, 177));
        lbl_sub.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_sub.setText("Entre informando os dados abaixo");

        pwf_senha.setBackground(new java.awt.Color(0, 2, 50));
        pwf_senha.setForeground(new java.awt.Color(204, 204, 204));
        pwf_senha.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(182, 137, 176)));

        txf_usuario.setBackground(new java.awt.Color(0, 2, 50));
        txf_usuario.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        txf_usuario.setForeground(new java.awt.Color(204, 204, 204));
        txf_usuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txf_usuario.setToolTipText("");
        txf_usuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(182, 137, 176)));

        lbl_esqueci_senha.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        lbl_esqueci_senha.setForeground(new java.awt.Color(182, 137, 176));
        lbl_esqueci_senha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_esqueci_senha.setText("Esqueci a senha");
        lbl_esqueci_senha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn_entrar.setBackground(new java.awt.Color(182, 137, 176));
        btn_entrar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btn_entrar.setForeground(new java.awt.Color(235, 235, 235));
        btn_entrar.setText("Entrar");
        btn_entrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(182, 137, 176), 0, true));
        btn_entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_entrar.setFocusPainted(false);

        lbl_sub1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lbl_sub1.setForeground(new java.awt.Color(94, 100, 177));
        lbl_sub1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_sub1.setText("Não tem uma conta?");

        lbl_esqueci_senha1.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        lbl_esqueci_senha1.setForeground(new java.awt.Color(182, 137, 176));
        lbl_esqueci_senha1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_esqueci_senha1.setText("CRIAR CONTA");
        lbl_esqueci_senha1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pnl_title_bar.setBackground(new java.awt.Color(0, 2, 50));
        pnl_title_bar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnl_title_barMouseDragged(evt);
            }
        });
        pnl_title_bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_title_barMousePressed(evt);
            }
        });

        btn_minimizar.setBackground(new java.awt.Color(182, 137, 176));
        btn_minimizar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_minimizar.setForeground(new java.awt.Color(255, 255, 255));
        btn_minimizar.setText("__");
        btn_minimizar.setBorder(null);
        btn_minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_minimizar.setFocusPainted(false);
        btn_minimizar.setSelected(true);
        btn_minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_minimizarActionPerformed(evt);
            }
        });

        btn_sair.setBackground(new java.awt.Color(182, 137, 176));
        btn_sair.setForeground(new java.awt.Color(255, 255, 255));
        btn_sair.setText("X");
        btn_sair.setBorder(null);
        btn_sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_sair.setFocusPainted(false);
        btn_sair.setSelected(true);
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_title_barLayout = new javax.swing.GroupLayout(pnl_title_bar);
        pnl_title_bar.setLayout(pnl_title_barLayout);
        pnl_title_barLayout.setHorizontalGroup(
            pnl_title_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_title_barLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        pnl_title_barLayout.setVerticalGroup(
            pnl_title_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_title_barLayout.createSequentialGroup()
                .addGroup(pnl_title_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        lbl_avatar.setIcon(new javax.swing.ImageIcon("/home/marcelo/Documentos/GitHub/Projeto_Ferias/Projeto_Ferias/icons/icon_avatar.png")); // NOI18N

        lbl_user_icon.setIcon(new javax.swing.ImageIcon("/home/marcelo/Documentos/GitHub/Projeto_Ferias/Projeto_Ferias/icons/user-icon.png")); // NOI18N

        lbl_padlock.setIcon(new javax.swing.ImageIcon("/home/marcelo/Documentos/GitHub/Projeto_Ferias/Projeto_Ferias/icons/padlock.png")); // NOI18N

        javax.swing.GroupLayout pnl_bgLayout = new javax.swing.GroupLayout(pnl_bg);
        pnl_bg.setLayout(pnl_bgLayout);
        pnl_bgLayout.setHorizontalGroup(
            pnl_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_title_bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnl_bgLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(lbl_avatar)
                .addGap(0, 135, Short.MAX_VALUE))
            .addGroup(pnl_bgLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnl_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txf_usuario)
                    .addComponent(pwf_senha, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_entrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_sub1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_bgLayout.createSequentialGroup()
                        .addGroup(pnl_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_padlock)
                            .addComponent(lbl_user_icon))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lbl_esqueci_senha1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_esqueci_senha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_sub, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_bem_vindo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        pnl_bgLayout.setVerticalGroup(
            pnl_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_bgLayout.createSequentialGroup()
                .addComponent(pnl_title_bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(lbl_avatar)
                .addGap(41, 41, 41)
                .addComponent(lbl_bem_vindo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_sub)
                .addGap(25, 25, 25)
                .addComponent(lbl_user_icon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(lbl_padlock)
                .addGap(1, 1, 1)
                .addComponent(pwf_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_esqueci_senha)
                .addGap(35, 35, 35)
                .addComponent(btn_entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(lbl_sub1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_esqueci_senha1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        //Fecha a janela
        this.dispose();
    }//GEN-LAST:event_btn_sairActionPerformed

    private void pnl_title_barMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_title_barMousePressed
        // TODO add your handling code here:
        //Pega as informações de onde está o mouse quando pressionado
        if (evt.getButton() ==  java.awt.event.MouseEvent.BUTTON1) {
            LayoutX = evt.getX();
            LayoutY = evt.getY();
        }
    }//GEN-LAST:event_pnl_title_barMousePressed

    private void pnl_title_barMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_title_barMouseDragged
        // TODO add your handling code here:
        //Passa as informações de onde está o mouse pressionado para a janela
            this.setLocation(evt.getXOnScreen()-LayoutX,evt.getYOnScreen()-LayoutY);
    }//GEN-LAST:event_pnl_title_barMouseDragged

    private void btn_minimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_minimizarActionPerformed
        // TODO add your handling code here:
        //Minimiza a janela
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btn_minimizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FLatLak Light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_entrar;
    private javax.swing.JButton btn_minimizar;
    private javax.swing.JButton btn_sair;
    private javax.swing.JLabel lbl_avatar;
    private javax.swing.JLabel lbl_bem_vindo;
    private javax.swing.JLabel lbl_esqueci_senha;
    private javax.swing.JLabel lbl_esqueci_senha1;
    private javax.swing.JLabel lbl_padlock;
    private javax.swing.JLabel lbl_sub;
    private javax.swing.JLabel lbl_sub1;
    private javax.swing.JLabel lbl_user_icon;
    private javax.swing.JPanel pnl_bg;
    private javax.swing.JPanel pnl_title_bar;
    private javax.swing.JPasswordField pwf_senha;
    private javax.swing.JTextField txf_usuario;
    // End of variables declaration//GEN-END:variables
}
